#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

#    .---------- constant part!
#    vvvv vvvv-- the code from above
RED='\033[0;31m'
NC='\033[0m' # No Color
echo "${RED}Husky:${NC} Pre-commit"
npx tsc
echo "${RED}Husky:${NC} TSC checked"
